In [2]:
from finance_complaint.config.spark_manager import spark_session

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/06/24 05:07:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
data_dir="D:/real-time-projects/backup26_03/finance_artifact_for doc/data_ingestion/20260402_143422/downloaded_files"

In [4]:
import os

In [28]:
def convert_files_to_parquet() -> str:
    
 
        json_data_dir="../finance_artifact/data_ingestion/20260402_143422/downloaded_files"
        data_dir = "../finance_artifact/data_ingestion/feature_store"
        output_file_name = "finance_complaint"
        os.makedirs(data_dir, exist_ok=True)
        print("Current working directory:", os.getcwd())
        print("JSON dir:", json_data_dir)
        print("Exists:", os.path.exists(json_data_dir))
        file_path = os.path.join(data_dir, f"{output_file_name}")
        
        if not os.path.exists(json_data_dir):
            return file_path
        for file_name in os.listdir(json_data_dir):
            json_file_path = os.path.join(json_data_dir, file_name)
            
            df = spark_session.read.json(json_file_path)
            print(df.count())
            if df.count() > 0:
                df.write.mode('append').parquet(file_path)
                print("write success")
        return file_path

In [29]:
path=convert_files_to_parquet()
path

Current working directory: /app/notebook
JSON dir: ../finance_artifact/data_ingestion/20260402_143422/downloaded_files
Exists: True

242958

write success

257385

write success

277765

write success

444986

write success

497184

write success

26/06/24 05:49:46 ERROR Executor: Exception in task 0.0 in stage 40.0 (TID 250)]
java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:80)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.grow(UnsafeWriter.java:63)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.writeUnalignedBytes(UnsafeWriter.java:127)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.write(UnsafeWriter.java:110)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.$anonfun$apply$1(FileFormat.scala:149)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1$$Lambda$2764/68369138.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:107)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:80)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema$$Lambda$2421/212056145.apply(Unknown Source)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.RDD$$Lambda$2422/1558276751.apply(Unknown Source)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
26/06/24 05:49:46 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 0.0 in stage 40.0 (TID 250),5,main]
java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:80)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.grow(UnsafeWriter.java:63)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.writeUnalignedBytes(UnsafeWriter.java:127)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.write(UnsafeWriter.java:110)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.$anonfun$apply$1(FileFormat.scala:149)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1$$Lambda$2764/68369138.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:107)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:80)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema$$Lambda$2421/212056145.apply(Unknown Source)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.RDD$$Lambda$2422/1558276751.apply(Unknown Source)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
26/06/24 05:49:46 WARN TaskSetManager: Lost task 0.0 in stage 40.0 (TID 250) (3c2313c52b87 executor driver): java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:80)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.grow(UnsafeWriter.java:63)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.writeUnalignedBytes(UnsafeWriter.java:127)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.write(UnsafeWriter.java:110)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.$anonfun$apply$1(FileFormat.scala:149)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1$$Lambda$2764/68369138.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:107)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.isEmpty(Iterator.scala:387)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:387)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:80)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema$$Lambda$2421/212056145.apply(Unknown Source)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.RDD$$Lambda$2422/1558276751.apply(Unknown Source)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)

26/06/24 05:49:46 ERROR TaskSetManager: Task 0 in stage 40.0 failed 1 times; aborting job
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: <unprintable Py4JJavaError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/py4j/clientserver.py", line 480, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.8/dist-packages/py4j/clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/py4j/clientserver.py", line 480, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.8/dist-packages/py4j/clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving

Py4JError: An error occurred while calling z:org.apache.spark.util.Utils.exceptionString

In [11]:
for file_name in os.listdir("downloaded_dir"):
    df = spark.read.json(f'downloaded_dir/{file_name}')
    df.write.mode('append').parquet("complaint_data")

In [12]:
df=spark.read.parquet("complaint_data")

In [13]:
df.count()

2786775

In [14]:
df.printSchema()

root
 |-- company: string (nullable = true)
 |-- company_public_response: string (nullable = true)
 |-- company_response: string (nullable = true)
 |-- complaint_id: string (nullable = true)
 |-- complaint_what_happened: string (nullable = true)
 |-- consumer_consent_provided: string (nullable = true)
 |-- consumer_disputed: string (nullable = true)
 |-- date_received: string (nullable = true)
 |-- date_sent_to_company: string (nullable = true)
 |-- issue: string (nullable = true)
 |-- product: string (nullable = true)
 |-- state: string (nullable = true)
 |-- sub_issue: string (nullable = true)
 |-- sub_product: string (nullable = true)
 |-- submitted_via: string (nullable = true)
 |-- tags: string (nullable = true)
 |-- timely: string (nullable = true)
 |-- zip_code: string (nullable = true)

In [19]:
df.select("consumer_disputed").distinct().show()

+-----------------+
|consumer_disputed|
+-----------------+
|              N/A|
|               No|
|              Yes|
+-----------------+

In [22]:
df.groupby("consumer_disputed").count().show()

+-----------------+-------+
|consumer_disputed|  count|
+-----------------+-------+
|              N/A|2017177|
|               No| 621087|
|              Yes| 148511|
+-----------------+-------+

In [25]:
df.groupby("company").count().count()

6464

In [35]:
df.groupby("company","product").count().show()

+--------------------+--------------------+-----+
|             company|             product|count|
+--------------------+--------------------+-----+
|           AFNI INC.|     Debt collection| 3817|
|CARTER-JONES COLL...|Credit reporting,...|    2|
|Byrider Franchisi...|Vehicle loan or l...|  214|
|PENNYMAC LOAN SER...|Credit reporting,...|  163|
|MERCANTILE ADJUST...|     Debt collection|  393|
|SECURITY FINANCE ...|Payday loan, titl...|  122|
|   Happy Money, Inc.|Payday loan, titl...|   41|
|Nationwide Judgem...|     Debt collection|    4|
|  LJ Ross Associates|     Debt collection|  525|
|Real Time Group, ...|            Mortgage|  383|
|BETHPAGE FEDERAL ...|Credit reporting,...|    7|
|Liberty Career Fi...|     Debt collection|    1|
|Advance America, ...|Payday loan, titl...|  192|
|Stratus Financial...|Payday loan, titl...|    1|
|CONTOUR MORTGAGE ...|            Mortgage|   26|
|Volvo Car Financi...|     Debt collection|    3|
|     BTS Motors, LLC|Credit reporting,...|    3|
|     ATG Credit, LLC|Credit reporting,...|   57|
|Top Flight Assist...|Credit reporting,...|    3|
|ADIR INTERNATIONA...|Credit card or pr...|   20|
+--------------------+--------------------+-----+
only showing top 20 rows

In [39]:
summary_df = df.summary().toPandas()

In [40]:
summary_df

,summary,company,company_public_response,company_response,complaint_id,complaint_what_happened,consumer_consent_provided,consumer_disputed,date_received,date_sent_to_company,issue,product,state,sub_issue,sub_product,submitted_via,tags,timely,zip_code
0,count,2786775,1214892,2786772,2786775,2786775,2785741,2786775,2786775,2786775,2786775,2786775,2746700,2119778,2551669,2786775,324664,2786775,2746415
1,mean,None,None,None,3242387.0996244764,None,None,None,None,None,None,None,None,None,None,None,None,None,48648.906201801095
2,stddev,None,None,None,1480652.6945187128,None,None,None,None,None,None,None,None,None,None,None,None,None,29682.57870967089
3,min,"(Former)Shapiro, Swertfeger & Hasty, LLP",Company believes complaint caused principally ...,Closed,1,,Consent not provided,N/A,2011-12-31T12:00:00-05:00,2011-12-30T12:00:00-05:00,APR or interest rate,Bank account or service,AA,Account information incorrect,(CD) Certificate of deposit,Email,Older American,No,(1352
4,25%,None,None,None,2269254.0,None,None,None,None,None,None,None,None,None,None,None,None,None,27106.0
5,50%,None,None,None,3373403.0,None,None,None,None,None,None,None,None,None,None,None,None,None,38008.0
6,75%,None,None,None,4358891.0,None,None,None,None,None,None,None,None,None,None,None,None,None,77301.0
7,max,"Lippman Recupero, LLC",Company has responded to the consumer and the ...,Untimely response,99999,•\tSchool Loan servicer XXXX defaulted my loa...,Other,Yes,2022-06-30T12:00:00-05:00,2022-09-01T12:00:00-05:00,Wrong amount charged or received,Virtual currency,WY,"You told them to stop contacting you, but they...",Virtual currency,Web Referral,Servicemember,Yes,9`325

In [1]:
import pandas as pd

In [2]:
new_df = pd.read_parquet("complaint_data")

In [3]:
del df

NameError: name 'df' is not defined

In [45]:
new_df.describe()

,company,company_public_response,company_response,complaint_id,complaint_what_happened,consumer_consent_provided,consumer_disputed,date_received,date_sent_to_company,issue,product,state,sub_issue,sub_product,submitted_via,tags,timely,zip_code
count,2786775,1214892,2786772,2786775,2786775,2785741,2786775,2786775,2786775,2786775,2786775,2746700,2119778,2551669,2786775,324664,2786775,2746415
unique,6464,11,8,2774363,892229,5,3,3833,3834,165,18,63,221,76,7,3,2,34117
top,"EQUIFAX, INC.",Company has responded to the consumer and the ...,Closed with explanation,3723751,,Consent provided,N/A,2021-06-30T12:00:00-05:00,2022-05-03T12:00:00-05:00,Incorrect information on your report,"Credit reporting, credit repair services, or o...",CA,Information belongs to someone else,Credit reporting,Web,Servicemember,Yes,30349
freq,455020,1012944,2240472,2,1766557,1020820,2017177,3750,3653,671106,1184879,347535,428265,1170768,2303573,176861,2738213,4389

In [47]:
new_df.consumer_disputed.value_counts()

N/A    2017177
No      621087
Yes     148511
Name: consumer_disputed, dtype: int64

In [4]:
import matplotlib.pyplot as plt

In [5]:
company_name = new_df.company.value_counts().head().index.array

In [6]:
company_count = new_df.company.value_counts().head().array

In [7]:
import matplotlib.pyplot as plt

In [14]:
import numpy as np

In [16]:
new_df.replace("None",np.nan,inplace=True)

In [26]:
new_df.replace("N/A",np.nan,inplace=True)

In [28]:
new_df.replace("",np.nan,inplace=True)

In [32]:
new_df.dropna(inplace=True)

In [33]:
new_df.shape

(3132, 18)

In [35]:
new_df.consumer_disputed.value_counts()

No     2463
Yes     669
Name: consumer_disputed, dtype: int64

In [36]:
new_df

,company,company_public_response,company_response,complaint_id,complaint_what_happened,consumer_consent_provided,consumer_disputed,date_received,date_sent_to_company,issue,product,state,sub_issue,sub_product,submitted_via,tags,timely,zip_code
638449,"CCS Financial Services, Inc.",Company believes the complaint is the result o...,Closed with explanation,1438902,On XXXX XXXX. 2015 a representative from CCS c...,Consent provided,No,2015-06-25T12:00:00-05:00,2015-06-25T12:00:00-05:00,Communication tactics,Debt collection,TX,Frequent or repeated calls,"Other (i.e. phone, health club, etc.)",Web,Older American,Yes,75104
638487,"Meade & Associates, Inc.",Company believes it acted appropriately as aut...,Closed,1370704,I submitted this to the CFPB about 6 months ag...,Consent provided,No,2015-05-12T12:00:00-05:00,2015-05-12T12:00:00-05:00,Cont'd attempts collect debt not owed,Debt collection,OH,Debt is not mine,"Other (i.e. phone, health club, etc.)",Web,Older American,Yes,43230
638880,Financial Credit Network Inc,Company believes the complaint is the result o...,Closed with explanation,1351396,Says medical services were rendered in XX/XX/X...,Consent provided,Yes,2015-04-28T12:00:00-05:00,2015-04-28T12:00:00-05:00,False statements or representation,Debt collection,CA,Attempted to collect wrong amount,Medical,Web,Servicemember,Yes,90025
639177,"Altisource Portfolio Solutions, S.à r.l.",Company believes it acted appropriately as aut...,Closed with explanation,1356307,Nationwide Credit INC. called to say if i paid...,Consent provided,No,2015-05-01T12:00:00-05:00,2015-05-01T12:00:00-05:00,Cont'd attempts collect debt not owed,Debt collection,FL,Debt was paid,Credit card,Web,Servicemember,Yes,34243
639776,"RS Clark and Associates, Inc.",Company believes it acted appropriately as aut...,Closed with explanation,1385669,This debt has shown up on my credit report ( s...,Consent provided,No,2015-05-20T12:00:00-05:00,2015-05-27T12:00:00-05:00,Cont'd attempts collect debt not owed,Debt collection,AZ,Debt is not mine,"Other (i.e. phone, health club, etc.)",Web,Servicemember,Yes,85704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649658,"Allied Collection Services, Inc. (Nevada)",Company chooses not to provide a public response,Closed with explanation,1500006,"My wife gave birth to our son in XXXX, 2014, w...",Consent provided,No,2015-08-03T12:00:00-05:00,2015-08-03T12:00:00-05:00,Disclosure verification of debt,Debt collection,NV,Right to dispute notice not received,Medical,Web,Servicemember,Yes,89134
2649731,"BANK OF AMERICA, NATIONAL ASSOCIATION",Company chooses not to provide a public response,Closed with explanation,1581170,I have no contract with this 3rd party debt co...,Consent provided,No,2015-09-25T12:00:00-05:00,2015-09-25T12:00:00-05:00,False statements or representation,Debt collection,DE,Impersonated an attorney or official,Mortgage,Web,Servicemember,Yes,19701
2649756,"McCullough Payne & Haan, LLC",Company chooses not to provide a public response,Closed with explanation,1639359,XXXX XXXX and assigned lawyers suing for debt ...,Consent provided,Yes,2015-11-04T12:00:00-05:00,2015-11-04T12:00:00-05:00,Disclosure verification of debt,Debt collection,AL,Not given enough info to verify debt,Credit card,Web,Older American,Yes,35080
2649804,"FLAGSTAR BANK, FSB",Company chooses not to provide a public response,Closed with explanation,1534563,XXXX XXXX I purchased ( paid cash ) a home fro...,Consent provided,No,2015-08-25T12:00:00-05:00,2015-08-25T12:00:00-05:00,Cont'd attempts collect debt not owed,Debt collection,AZ,Debt is not mine,Mortgage,Web,Older American,Yes,85132
2650316,"Account Control Technology, Inc.",Company believes it acted appropriately as aut...,Closed with non-monetary relief,1642277,Illegal and Improper contact from third party ...,Consent provided,Yes,2015-11-04T12:00:00-05:00,2015-11-04T12:00:00-05:00,Cont'd attempts collect debt not owed,Debt collection,DE,Debt was discharged in bankruptcy,Federal student loan,Web,Servicemember,Yes,19701

In [37]:
max(new_df.company_response.apply(lambda x: len(x)))

31

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

ModuleNotFoundError: No module named 'sklearn'

In [39]:
from pyspark.sql import SparkSession